name: Coverage

on:
  push:
    branches: [ master ]

env:
  SHORTY_ADMIN_KEY: ${{ vars.ENV_CONTEXT_VAR }}
  SHORTY_EMAIL_KEY: ${{ vars.ENV_CONTEXT_VAR }}
  SHORTY_EMAIL: ${{ vars.ENV_CONTEXT_VAR }}
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - run: echo "Automate Job for PyTest on push/pull"
      - uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11
      - name: Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: run PyTest
        run: python -m pytest --cov .
      - name: Creating Badge
        run: |
          python -m pip install coverage-badge
          coverage-badge -o coverage.svg -f
      - name: Upload badge
        uses: actions/upload-artifact@v3
        with:
          path: /home/runner/work/FastAPI_UrlShort/FastAPI_UrlShort/coverage.svg
      - name: Commit badge
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Github Action"
          git add coverage.svg 
          git diff-index --quiet HEAD || commit -m "Add/Update coverage"
      - name: Push badge commit
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ steps.extract_branch.outputs.branch }}
